// Generated by CoffeeScript 1.7.1
var JSON5, cluster, error, fs, os, path, print, _, _ref;

_ = require('lodash');

os = require('os');

fs = require('fs');

path = require('path');

JSON5 = require('json5');

cluster = require('cluster');

_ref = require('util'), error = _ref.error, print = _ref.print;

exports.conversion = function(str) {
  if (_.isNull(str)) {
    return null;
  }
  str = str.replace(/%h/g, process.env.HOME).replace(/%d/g, process.cwd()).replace(/%p/g, process.env.PORT).replace(/%e/g, process.env.NODE_ENV);
  if (cluster.isWorker) {
    str = str.replace(/%t/g, process.env.EMA_TITLE).replace(/%c/g, process.env.EMA_CLUSTER).replace(/%C/g, process.env.EMA_CLUSTERS);
  }
  return str.replace(/%%/g, '%').replace(/%[a-z]/gi, '');
};

exports.descendant = function(obj, desc) {
  var descs;
  descs = desc.split('.');
  while (descs.length && descs.length && (obj = obj[descs.shift()])) {
    continue;
  }
  return obj;
};

exports.safeforlog = function(dst, options) {
  if (options == null) {
    options = {};
  }
  if (options.allowNull && dst === null) {
    return true;
  }
  if ((fs.existsSync(dst)) && (fs.statSync(dst)).isDirectory()) {
    return false;
  }
  if ((fs.existsSync(path.dirname(dst))) && (fs.statSync(path.dirname(dst))).isFile()) {
    return false;
  }
  return true;
};

exports.configuration = function(program, defaults) {
  var access_log_inherit, clustering_inherit, config, directives, err, error_log_inherit, ext, title, verbose, _i, _len, _ref1, _ref2, _ref3, _ref4, _ref5;
  try {
    if (_.isString(program.directives)) {
      program.directives = program.directives.trim();
      if (!/^{/.test(program.directives)) {
        program.directives = "{" + program.directives;
      }
      if (!/}$/.test(program.directives)) {
        program.directives = "" + program.directives + "}";
      }
      program.directives = _.defaults(JSON5.parse(program.directives), defaults.global);
    }
    verbose = program.test && !program.quiet;
    _ref1 = ['', '.json', '.json5', null];
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      ext = _ref1[_i];
      if (_.isNull(ext)) {
        error("configuration file '" + program.config + "' not found.");
        process.exit(1);
      }
      if (fs.existsSync(config = path.resolve(program.config + ext))) {
        directives = _.extend(program.directives, JSON5.parse(fs.readFileSync(config, 'utf-8')));
        program.directives = _.pick(directives, ['name', 'pid_path', 'access_log', 'error_log', 'clustering', 'timeout', 'server']);
        program.directives.pid_path = exports.conversion(program.directives.pid_path);
        if (!exports.safeforlog(program.directives.pid_path, {
          allowNull: false
        })) {
          throw new Error("'pid_path' should be writeable path");
        } else if (verbose) {
          print("✓ 'pid_path' is valid [" + program.directives.pid_path + "]\n");
        }
        program.directives.access_log = exports.conversion(program.directives.access_log);
        if (!exports.safeforlog(program.directives.access_log, {
          allowNull: true
        })) {
          throw new Error("'access_log' should be writeable path");
        } else if (verbose) {
          print("✓ 'access_log' is valid [" + program.directives.access_log + "]\n");
        }
        program.directives.error_log = exports.conversion(program.directives.error_log);
        if (!exports.safeforlog(program.directives.error_log, {
          allowNull: true
        })) {
          throw new Error("'error_log' should be writeable path");
        } else if (verbose) {
          print("✓ 'error_log' is valid [" + program.directives.error_log + "]\n");
        }
        if (program.directives.clustering === 'auto') {
          program.directives.clustering = os.cpus().length;
        } else {
          program.directives.clustering = parseInt(program.directives.clustering, 10);
        }
        if (!_.isNumber(program.directives.clustering)) {
          throw new Error("'clustering' should be a number");
        } else if (verbose) {
          print("✓ 'clustering' is valid [" + program.directives.clustering + "]\n");
        }
        if (!_.isNumber(program.directives.timeout)) {
          throw new Error("'timeout' should be a number");
        } else if (verbose) {
          print("✓ 'timeout' is valid [" + program.directives.timeout + "]\n");
        }
        if (!((_.isObject(program.directives.server)) && 0 < (_.keys(program.directives.server)).length)) {
          throw new Error("'server' should be valid object\n");
        } else if (verbose) {
          print("✓ 'server' is valid object [{" + (_.keys(program.directives.server).join(',')) + "}]\n");
        }
        break;
      }
    }
    _ref2 = program.directives.server;
    for (title in _ref2) {
      config = _ref2[title];
      program.directives.server[title] = _.defaults(program.directives.server[title], defaults.server);
      program.directives.server[title] = _.pick(program.directives.server[title], ['access_log', 'error_log', 'clustering', 'script', 'match_env', 'unmatch_env', 'env']);
      if (_.isNull(program.directives.server[title].script)) {
        throw new Error("'server." + title + ".script' should be file");
      }
      program.directives.server[title].script = path.resolve(program.directives.server[title].script);
      if (!fs.existsSync(program.directives.server[title].script)) {
        throw new Error("'server." + title + ".script' should be exists");
      } else if (verbose) {
        print("✓ 'server." + title + ".script' exists [" + program.directives.server[title].script + "]\n");
      }
      access_log_inherit = false;
      if ((_ref3 = program.directives.server[title].access_log) === null || _ref3 === 'inherit') {
        access_log_inherit = true;
        program.directives.server[title].access_log = program.directives.access_log;
      }
      error_log_inherit = false;
      if ((_ref4 = program.directives.server[title].error_log) === null || _ref4 === 'inherit') {
        error_log_inherit = true;
        program.directives.server[title].error_log = program.directives.error_log;
      }
      clustering_inherit = false;
      if ((_ref5 = program.directives.server[title].clustering) === 'auto' || _ref5 === 'inherit') {
        clustering_inherit = true;
        program.directives.server[title].clustering = program.directives.clustering;
      }
      if (!_.isNumber(program.directives.server[title].clustering)) {
        throw new Error("'server." + title + ".clustering' should be a number");
      } else if (verbose) {
        print("✓ 'server." + title + ".clustering' is valid [" + program.directives.server[title].clustering + (clustering_inherit ? ' (inherit)' : void 0) + "]\n");
      }
      if (_.isString(program.directives.server[title].match_env)) {
        try {
          if (program.directives.server[title].match_env) {
            program.directives.server[title].match_env = new RegExp(program.directives.server[title].match_env);
          }
        } catch (_error) {
          err = _error;
          throw new Error("'server." + title + ".match_env' should be valid regular expression");
        }
        if (verbose) {
          print("✓ 'server." + title + ".match_env' is valid [" + program.directives.server[title].match_env + "]\n");
        }
      }
      if (_.isString(program.directives.server[title].unmatch_env)) {
        try {
          if (program.directives.server[title].unmatch_env) {
            program.directives.server[title].unmatch_env = new RegExp(program.directives.server[title].unmatch_env);
          }
        } catch (_error) {
          err = _error;
          throw new Error("'server." + title + ".unmatch_env' should be valid regular expression");
        }
        if (verbose) {
          print("✓ 'server." + title + ".unmatch_env' is valid [" + program.directives.server[title].unmatch_env + "]\n");
        }
      }
      if (!_.isObject(program.directives.server[title].env)) {
        throw new Error("'server'." + title + ".env' should be object");
      }
    }
  } catch (_error) {
    err = _error;
    error("! " + err.message);
    error("configuration file '" + program.config + "' test is failed");
    process.exit(1);
  }
  if (program.test) {
    print("configuration file '" + program.config + "' test is successful\n");
    process.exit(0);
  }
  return program;
};
